"""initial nine table schema

Revision ID: 1c9bd42e720f
Revises: 
Create Date: 2026-09-20 13:31:53.209004
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '1c9bd42e720f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund',
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manager_name', sa.String(length=200), nullable=False),
    sa.Column('strategy_family', sa.String(length=100), nullable=False),
    sa.Column('share_class', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('firm_aum_usd_cents', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('fund_id')
    )
    op.create_table('document',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('partner',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('disclosure_block_md', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('template_version', sa.String(length=16), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.PrimaryKeyConstraint('partner_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('terms',
    sa.Column('terms_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('mgmt_fee_bps', sa.BigInteger(), nullable=False),
    sa.Column('perf_fee_bps', sa.BigInteger(), nullable=False),
    sa.Column('hurdle_bps', sa.BigInteger(), nullable=False),
    sa.Column('high_water_mark', sa.Boolean(), nullable=False),
    sa.Column('lockup_months', sa.Integer(), nullable=False),
    sa.Column('notice_days', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_fact_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_terms_range_ordered'),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.PrimaryKeyConstraint('terms_id')
    )
    op.create_index('ix_terms_fund_effective', 'terms', ['fund_id', 'effective_from'], unique=False)
    op.create_table('extraction_run',
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd_micros', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.PrimaryKeyConstraint('extraction_run_id')
    )
    op.create_table('fact',
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=64), nullable=False),
    sa.Column('value_numeric', sa.BigInteger(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extractor', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(superseded_by IS NULL) = (status <> 'superseded')", name='ck_fact_supersede_pairing'),
    sa.CheckConstraint('(value_numeric IS NULL) <> (value_text IS NULL)', name='ck_fact_exactly_one_value'),
    sa.CheckConstraint('length(quote) >= 3', name='ck_fact_quote_present'),
    sa.CheckConstraint('page_no >= 1', name='ck_fact_page_no'),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.extraction_run_id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index('ix_fact_lookup', 'fact', ['fund_id', 'field_path', 'period', 'status'], unique=False)
    op.create_table('drift_event',
    sa.Column('drift_event_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=True),
    sa.Column('field_path', sa.String(length=64), nullable=True),
    sa.Column('prior_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('prior_fact_id', sa.UUID(), nullable=True),
    sa.Column('new_fact_id', sa.UUID(), nullable=True),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.ForeignKeyConstraint(['new_fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['prior_fact_id'], ['fact.fact_id'], ),
    sa.PrimaryKeyConstraint('drift_event_id')
    )
    op.create_index('ix_drift_fund_status', 'drift_event', ['fund_id', 'status'], unique=False)
    op.create_table('fund_period_metrics',
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('gross_return_bps', sa.BigInteger(), nullable=True),
    sa.Column('gross_return_bps_fact_id', sa.UUID(), nullable=True),
    sa.Column('net_return_bps', sa.BigInteger(), nullable=True),
    sa.Column('net_return_bps_fact_id', sa.UUID(), nullable=True),
    sa.Column('ytd_return_bps', sa.BigInteger(), nullable=True),
    sa.Column('ytd_return_bps_fact_id', sa.UUID(), nullable=True),
    sa.Column('nav_usd_cents', sa.BigInteger(), nullable=True),
    sa.Column('nav_usd_cents_fact_id', sa.UUID(), nullable=True),
    sa.Column('sharpe_36m', sa.BigInteger(), nullable=True),
    sa.Column('sharpe_36m_fact_id', sa.UUID(), nullable=True),
    sa.Column('max_drawdown_bps', sa.BigInteger(), nullable=True),
    sa.Column('max_drawdown_bps_fact_id', sa.UUID(), nullable=True),
    sa.Column('materialized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.ForeignKeyConstraint(['gross_return_bps_fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['max_drawdown_bps_fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['nav_usd_cents_fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['net_return_bps_fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['sharpe_36m_fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['ytd_return_bps_fact_id'], ['fact.fact_id'], ),
    sa.PrimaryKeyConstraint('fund_id', 'period'),
    sa.UniqueConstraint('fund_id', 'period', name='uq_metrics_fund_period')
    )
    op.create_table('artifact',
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('template_version', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('render_uri', sa.Text(), nullable=True),
    sa.Column('fact_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('guard_violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_by_drift_id', sa.UUID(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('cost_usd_micros', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('rendered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by_drift_id'], ['drift_event.drift_event_id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.fund_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.partner_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifact')
    op.drop_table('fund_period_metrics')
    op.drop_index('ix_drift_fund_status', table_name='drift_event')
    op.drop_table('drift_event')
    op.drop_index('ix_fact_lookup', table_name='fact')
    op.drop_table('fact')
    op.drop_table('extraction_run')
    op.drop_index('ix_terms_fund_effective', table_name='terms')
    op.drop_table('terms')
    op.drop_table('partner')
    op.drop_table('document')
    op.drop_table('fund')
    # ### end Alembic commands ###
